### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by stysan** [virejdasani/AR-RR#1]
I opened YouTube, then rickroll and nothing happened. Did you made me rickroll myself btw? :)

**Comment by virejdasani** [comment]
Haha, after opening the app, you have to point the camera at this image:
![target image](https://github.com/virejdasani/AR-RR/blob/master/Assets/RickRollAssets/RickRollImg.jpeg)              

Check this out if you don't get it:
https://www.youtube.com/watch?v=wNbb3LDrM-0

**Comment by stysan** [comment]
Thank you really much :)
